#!/bin/bash
# build a stable nightly and a trunk nightly

DOWNLOAD_DIR='/var/www/www.elgg.org/download/nightly'
PACKAGE_SCRIPT='/root/elgg-scripts/build/build.sh'
DATE=$(date +%Y%m%d)
TARGETS='master 1.8 1.7'

for TARGET in $TARGETS; do
	OUTPUT_DIR="${DOWNLOAD_DIR}/${TARGET}"
	OUTPUT_NAME="${TARGET}-nightly-${DATE}"
	if [ ! -d ${OUTPUT_DIR} ]; then
		mkdir ${OUTPUT_DIR}
	fi

	${PACKAGE_SCRIPT} ${TARGET} ${OUTPUT_NAME} ${OUTPUT_DIR}
done
